name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (adjustable for other environments)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (jq, yq, curl)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # Step 4: Create .env file with secrets and configurations
      - name: Create .env file
        run: |
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" > .env
          echo "SNYK_ENABLED=true" >> .env
          echo "SNYK_SEVERITY=high" >> .env
          echo "TRIVY_ENABLED=true" >> .env
          echo "TRIVY_SEVERITY=HIGH" >> .env
          echo "TRIVY_IGNORE_UNFIXED=false" >> .env
          echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> .env
          
          # Detect Dockerfile and set IMAGE_NAME dynamically
          if [[ -f Dockerfile ]]; then
            echo "IMAGE_NAME=project-specific-image:latest" >> .env
          else
            echo "IMAGE_NAME=ubuntu:latest" >> .env
          fi

      # Step 5: Build Docker image (if Dockerfile exists)
      - name: Build Docker image (optional)
        if: exists('Dockerfile')
        run: |
          docker build -t project-specific-image:latest .

      # Step 6: Run security scan script
      - name: Run security scan
        run: |
          chmod +x security-scan.sh
          ./security-scan.sh

      # Step 7: Upload scan results as artifacts
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            reports/report.html
            reports/high-severity.json
